# Generated by Django 5.2 on 2025-04-12 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_case_insensitive_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
