services:
  - type: web
    name: chat-app
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn WebChat.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: SECRET_KEY
        value: your-secret-key
      - key: DEBUG
        value: 'False'
      - key: ALLOWED_HOSTS
        value: 'yourdomain.com,localhost'
      - key: PYTHONPATH
        value: "/opt/render/project/src/WebChat"